// initialization of TODOS
export const TODOS_ACTION_STARTED = "TODOS_ACTION_STARTED";
export type TODOS_ACTION_STARTED = typeof TODOS_ACTION_STARTED;

export const INIT_TODOS_SUCCESS = "INIT_TODOS_SUCCESS";
export type INIT_TODOS_SUCCESS = typeof INIT_TODOS_SUCCESS;

export const TODOS_ACTION_ERROR = "TODOS_ACTION_ERROR";
export type TODOS_ACTION_ERROR = typeof TODOS_ACTION_ERROR;

//complete Todos

export const COMPLETE_TODOS_SUCCESS = "COMPLETE_TODOS_SUCCESS";
export type COMPLETE_TODOS_SUCCESS = typeof COMPLETE_TODOS_SUCCESS;

export const UNCOMPLETE_TODOS_SUCCESS = "UNCOMPLETE_TODOS_SUCCESS";
export type UNCOMPLETE_TODOS_SUCCESS = typeof UNCOMPLETE_TODOS_SUCCESS;
